### PR TITLE
Update to 3.4.2

### PR DESCRIPTION
**Pull request by dbast**

### CODE REVIEW

**Review by pseudoyim — APPROVED** [review]

**Comment by cbouss** [comment]
@dbast FYI The process of updating the tag on constructor after this has been merge prevents rebuilding form the same recipe.

**Comment by dbast** [comment]
@cbouss hm, the tag should not change after the release. What makes you assume it did?

**Comment by dbast** [comment]
Checked... the tag did not change (it is also gpg signed) ... but there are very rare cases where the sha256 of the github tarball change without any changes in the repo.... the github tarball creation normally is very stable and consistent, but it changed 3 hours after the release... no idea why (Github had some other issues yesterday not sure if they caused that)

**Comment by dbast** [comment]
Googling for "GitHub release sha256 changed" gives a lot of findings. tldr; this happens rarely with not solution (except uploading a dedicated tarball to the release artifacts created by CI and not relying on what GitHub provides)

**Comment by cbouss** [comment]
Hmm I don't see it often, but I noticed this recently on constructor, conda and conda-build. I had hoped there'd be a pattern we could address. I'll update the sha then.

**Pull request merged**
